### ISSUE TITLE
Creating app.py for parsing Codechef contests

### ISSUE THREAD

**Issue by suyash-chavan** [suyash-chavan/Contest-Parser#8]
Create app.py as created for Codeforces parser.

**Comment by suyash-chavan** [comment]
Reference: https://github.com/Sakshisrivastava413/codechef_problem_scrapper/blob/master/scrap.py

**Comment by rising-entropy** [comment]
I guess, I can do it.
Please assign it to me.

**Comment by suyash-chavan** [comment]
Hi @rising-entropy, please check https://github.com/suyash-chavan/Contest-Parser/blob/main/manager_flow.png

You need to create these files in Codechef folder:
generator.py - A web scrapping script for Codechef (refer app.py in Codeforces folder)
settings.json - To hold programming language of workspace, contests in workspace,  path of cp template folder.
judge.py - Judge for a question (refer chhecker.py in Codeforces folder)

Scope of manipulator is broader and will think on what and how it will manipulate the files.

Thankyou!

**Comment by suyash-chavan** [comment]
Also try if you can keep generator.py at manager level and generate files at a workspace path by giving path as a command line argument.

**Comment by rising-entropy** [comment]
Yep, I'll try to make it similar to CodeForces one at first, then we'll take it from there.

**Comment by suyash-chavan** [comment]
Ok

**Comment by suyash-chavan** [comment]
PR by @rising-entropy - #16.
